# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/SpaceShooter/SpaceShooter.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SpaceShooter || ORIG_REF_NAME==SpaceShooter} -quiet] -quiet

# IP: bd/SpaceShooter/ip/SpaceShooter_proc_sys_reset_0_0_2/SpaceShooter_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SpaceShooter_proc_sys_reset_0_0 || ORIG_REF_NAME==SpaceShooter_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/SpaceShooter/ip/SpaceShooter_clk_wiz_0_0_2/SpaceShooter_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SpaceShooter_clk_wiz_0_0 || ORIG_REF_NAME==SpaceShooter_clk_wiz_0_0} -quiet] -quiet

# IP: bd/SpaceShooter/ip/SpaceShooter_AXI4Stream_UART_0_0_2/SpaceShooter_AXI4Stream_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SpaceShooter_AXI4Stream_UART_0_0 || ORIG_REF_NAME==SpaceShooter_AXI4Stream_UART_0_0} -quiet] -quiet

# IP: bd/SpaceShooter/ip/SpaceShooter_axi4stream_spi_master_0_0_2/SpaceShooter_axi4stream_spi_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SpaceShooter_axi4stream_spi_master_0_0 || ORIG_REF_NAME==SpaceShooter_axi4stream_spi_master_0_0} -quiet] -quiet

# IP: bd/SpaceShooter/ip/SpaceShooter_digilent_jstk2_0_0_2/SpaceShooter_digilent_jstk2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SpaceShooter_digilent_jstk2_0_0 || ORIG_REF_NAME==SpaceShooter_digilent_jstk2_0_0} -quiet] -quiet

# IP: bd/SpaceShooter/ip/SpaceShooter_jstk_uart_bridge_0_0_2/SpaceShooter_jstk_uart_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SpaceShooter_jstk_uart_bridge_0_0 || ORIG_REF_NAME==SpaceShooter_jstk_uart_bridge_0_0} -quiet] -quiet

# XDC: /home/stexo/Nextcloud/uni/Polimi/8_Semester/DESD/labs/DESD_LABS/SpaceShooter/SpaceShooter.gen/sources_1/bd/SpaceShooter/SpaceShooter_ooc.xdc
