set_property SRC_FILE_INFO {cfile:{C:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Jstk2_SpaceShooter/Jstk2_SpaceShooter.srcs/constrs_1/new/PINS.xdc} rfile:../../../Jstk2_SpaceShooter.srcs/constrs_1/new/PINS.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L2 [get_ports SPI_M_0_io0_io]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G2 [get_ports SPI_M_0_sck_io]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports SPI_M_0_ss_io]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J2 [get_ports SPI_M_0_io1_io]
