set_property SRC_FILE_INFO {cfile:{C:/Users/daido/Desktop/Polimi/Anno 4/DESD/LAB2/Color_Grey/Color_Grey.srcs/constrs_1/imports/new/Pins.xdc} rfile:../../../Color_Grey.srcs/constrs_1/imports/new/Pins.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B18 [get_ports usb_uart_rxd]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports usb_uart_txd]
