# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/LAB2/Color_Grey/Color_Grey.srcs/sources_1/bd/Color_Grey/ip/Color_Grey_proc_sys_reset_0_0/Color_Grey_proc_sys_reset_0_0.xci
# IP: The module: 'Color_Grey_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/LAB2/Color_Grey/Color_Grey.gen/sources_1/bd/Color_Grey/ip/Color_Grey_proc_sys_reset_0_0/Color_Grey_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Color_Grey_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/LAB2/Color_Grey/Color_Grey.gen/sources_1/bd/Color_Grey/ip/Color_Grey_proc_sys_reset_0_0/Color_Grey_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Color_Grey_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/LAB2/Color_Grey/Color_Grey.gen/sources_1/bd/Color_Grey/ip/Color_Grey_proc_sys_reset_0_0/Color_Grey_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Color_Grey_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/LAB2/Color_Grey/Color_Grey.srcs/sources_1/bd/Color_Grey/ip/Color_Grey_proc_sys_reset_0_0/Color_Grey_proc_sys_reset_0_0.xci
# IP: The module: 'Color_Grey_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/LAB2/Color_Grey/Color_Grey.gen/sources_1/bd/Color_Grey/ip/Color_Grey_proc_sys_reset_0_0/Color_Grey_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Color_Grey_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/LAB2/Color_Grey/Color_Grey.gen/sources_1/bd/Color_Grey/ip/Color_Grey_proc_sys_reset_0_0/Color_Grey_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Color_Grey_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/LAB2/Color_Grey/Color_Grey.gen/sources_1/bd/Color_Grey/ip/Color_Grey_proc_sys_reset_0_0/Color_Grey_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Color_Grey_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
