# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/test_UART_packet/test_UART_packet.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_UART_packet || ORIG_REF_NAME==test_UART_packet} -quiet] -quiet

# IP: bd/test_UART_packet/ip/test_UART_packet_clk_wiz_0_0/test_UART_packet_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_UART_packet_clk_wiz_0_0 || ORIG_REF_NAME==test_UART_packet_clk_wiz_0_0} -quiet] -quiet

# IP: bd/test_UART_packet/ip/test_UART_packet_proc_sys_reset_0_0/test_UART_packet_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_UART_packet_proc_sys_reset_0_0 || ORIG_REF_NAME==test_UART_packet_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/test_UART_packet/ip/test_UART_packet_AXI4Stream_UART_0_0/test_UART_packet_AXI4Stream_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_UART_packet_AXI4Stream_UART_0_0 || ORIG_REF_NAME==test_UART_packet_AXI4Stream_UART_0_0} -quiet] -quiet

# IP: bd/test_UART_packet/ip/test_UART_packet_jstk_uart_bridge_0_0_0/test_UART_packet_jstk_uart_bridge_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_UART_packet_jstk_uart_bridge_0_0_0 || ORIG_REF_NAME==test_UART_packet_jstk_uart_bridge_0_0_0} -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Test_UART_packet/Test_UART_packet.gen/sources_1/bd/test_UART_packet/test_UART_packet_ooc.xdc
