# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PINS.xdc

# Block Designs: bd/interface_bd/interface_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interface_bd || ORIG_REF_NAME==interface_bd} -quiet] -quiet

# IP: bd/interface_bd/ip/interface_bd_clk_wiz_0_0/interface_bd_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interface_bd_clk_wiz_0_0 || ORIG_REF_NAME==interface_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/interface_bd/ip/interface_bd_proc_sys_reset_0_0/interface_bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interface_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==interface_bd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/interface_bd/ip/interface_bd_AXI4Stream_UART_0_0/interface_bd_AXI4Stream_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interface_bd_AXI4Stream_UART_0_0 || ORIG_REF_NAME==interface_bd_AXI4Stream_UART_0_0} -quiet] -quiet

# IP: bd/interface_bd/ip/interface_bd_axi4stream_spi_master_0_0/interface_bd_axi4stream_spi_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interface_bd_axi4stream_spi_master_0_0 || ORIG_REF_NAME==interface_bd_axi4stream_spi_master_0_0} -quiet] -quiet

# IP: bd/interface_bd/ip/interface_bd_digilent_jstk2_0_0/interface_bd_digilent_jstk2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interface_bd_digilent_jstk2_0_0 || ORIG_REF_NAME==interface_bd_digilent_jstk2_0_0} -quiet] -quiet

# IP: bd/interface_bd/ip/interface_bd_jstk_uart_bridge_0_0/interface_bd_jstk_uart_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interface_bd_jstk_uart_bridge_0_0 || ORIG_REF_NAME==interface_bd_jstk_uart_bridge_0_0} -quiet] -quiet

# XDC: /home/stexo/Nextcloud/uni/Polimi/8_Semester/DESD/labs/DESD_LABS/Jstk2_SpaceShooter/Jstk2_SpaceShooter.gen/sources_1/bd/interface_bd/interface_bd_ooc.xdc
