--Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
----------------------------------------------------------------------------------
--Tool Version: Vivado v.2020.2 (lin64) Build 3064766 Wed Nov 18 09:12:47 MST 2020
--Date        : Fri May  5 15:43:49 2023
--Host        : unbound-phoenix running 64-bit unknown
--Command     : generate_target BlockDesign.bd
--Design      : BlockDesign
--Purpose     : IP block netlist
----------------------------------------------------------------------------------
