# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/Pins.xdc

# Block Designs: bd/Color_Grey/Color_Grey.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Color_Grey || ORIG_REF_NAME==Color_Grey} -quiet] -quiet

# IP: bd/Color_Grey/ip/Color_Grey_AXI4Stream_UART_0_0/Color_Grey_AXI4Stream_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Color_Grey_AXI4Stream_UART_0_0 || ORIG_REF_NAME==Color_Grey_AXI4Stream_UART_0_0} -quiet] -quiet

# IP: bd/Color_Grey/ip/Color_Grey_clk_wiz_0_0/Color_Grey_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Color_Grey_clk_wiz_0_0 || ORIG_REF_NAME==Color_Grey_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Color_Grey/ip/Color_Grey_proc_sys_reset_0_0/Color_Grey_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Color_Grey_proc_sys_reset_0_0 || ORIG_REF_NAME==Color_Grey_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Color_Grey/ip/Color_Grey_C2G_0_0/Color_Grey_C2G_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Color_Grey_C2G_0_0 || ORIG_REF_NAME==Color_Grey_C2G_0_0} -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/LAB2/Color_Grey/Color_Grey.gen/sources_1/bd/Color_Grey/Color_Grey_ooc.xdc
