# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PINs.xdc

# Block Designs: bd/BlockDesign/BlockDesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign || ORIG_REF_NAME==BlockDesign} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_clk_wiz_0_0/BlockDesign_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_clk_wiz_0_0 || ORIG_REF_NAME==BlockDesign_clk_wiz_0_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_proc_sys_reset_0_0/BlockDesign_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_proc_sys_reset_0_0 || ORIG_REF_NAME==BlockDesign_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_proc_sys_reset_1_0/BlockDesign_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_proc_sys_reset_1_0 || ORIG_REF_NAME==BlockDesign_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_digilent_jstk2_0_0/BlockDesign_digilent_jstk2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_digilent_jstk2_0_0 || ORIG_REF_NAME==BlockDesign_digilent_jstk2_0_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_axi4stream_spi_master_1_0/BlockDesign_axi4stream_spi_master_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_axi4stream_spi_master_1_0 || ORIG_REF_NAME==BlockDesign_axi4stream_spi_master_1_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_axis_dual_i2s_1_0/BlockDesign_axis_dual_i2s_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_axis_dual_i2s_1_0 || ORIG_REF_NAME==BlockDesign_axis_dual_i2s_1_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_VolumeController_0_0/BlockDesign_VolumeController_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_VolumeController_0_0 || ORIG_REF_NAME==BlockDesign_VolumeController_0_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_BalanceController_0_0/BlockDesign_BalanceController_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_BalanceController_0_0 || ORIG_REF_NAME==BlockDesign_BalanceController_0_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_MobileMean_0_0/BlockDesign_MobileMean_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_MobileMean_0_0 || ORIG_REF_NAME==BlockDesign_MobileMean_0_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_EdgeDetector_0_0/BlockDesign_EdgeDetector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_EdgeDetector_0_0 || ORIG_REF_NAME==BlockDesign_EdgeDetector_0_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_EdgeDetector_1_0/BlockDesign_EdgeDetector_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_EdgeDetector_1_0 || ORIG_REF_NAME==BlockDesign_EdgeDetector_1_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_Debouncer_0_0/BlockDesign_Debouncer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_Debouncer_0_0 || ORIG_REF_NAME==BlockDesign_Debouncer_0_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_Debouncer_1_0/BlockDesign_Debouncer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_Debouncer_1_0 || ORIG_REF_NAME==BlockDesign_Debouncer_1_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_MuteController_0_0/BlockDesign_MuteController_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_MuteController_0_0 || ORIG_REF_NAME==BlockDesign_MuteController_0_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_LedController_0_0/BlockDesign_LedController_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_LedController_0_0 || ORIG_REF_NAME==BlockDesign_LedController_0_0} -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/AuDiOcOnSoLe/AuDiOcOnSoLe.gen/sources_1/bd/BlockDesign/BlockDesign_ooc.xdc
