# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Test_UART_packet/Test_UART_packet.srcs/sources_1/bd/test_UART_packet/ip/test_UART_packet_clk_wiz_0_0/test_UART_packet_clk_wiz_0_0.xci
# IP: The module: 'test_UART_packet_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Test_UART_packet/Test_UART_packet.gen/sources_1/bd/test_UART_packet/ip/test_UART_packet_clk_wiz_0_0/test_UART_packet_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_UART_packet_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Test_UART_packet/Test_UART_packet.gen/sources_1/bd/test_UART_packet/ip/test_UART_packet_clk_wiz_0_0/test_UART_packet_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_UART_packet_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Test_UART_packet/Test_UART_packet.gen/sources_1/bd/test_UART_packet/ip/test_UART_packet_clk_wiz_0_0/test_UART_packet_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_UART_packet_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Test_UART_packet/Test_UART_packet.srcs/sources_1/bd/test_UART_packet/ip/test_UART_packet_clk_wiz_0_0/test_UART_packet_clk_wiz_0_0.xci
# IP: The module: 'test_UART_packet_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Test_UART_packet/Test_UART_packet.gen/sources_1/bd/test_UART_packet/ip/test_UART_packet_clk_wiz_0_0/test_UART_packet_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_UART_packet_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Test_UART_packet/Test_UART_packet.gen/sources_1/bd/test_UART_packet/ip/test_UART_packet_clk_wiz_0_0/test_UART_packet_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_UART_packet_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Test_UART_packet/Test_UART_packet.gen/sources_1/bd/test_UART_packet/ip/test_UART_packet_clk_wiz_0_0/test_UART_packet_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_UART_packet_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
