# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PINS.xdc

# Block Designs: bd/test_UART_packet/test_UART_packet.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_UART_packet || ORIG_REF_NAME==test_UART_packet} -quiet] -quiet

# IP: bd/test_UART_packet/ip/test_UART_packet_proc_sys_reset_0_1/test_UART_packet_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_UART_packet_proc_sys_reset_0_1 || ORIG_REF_NAME==test_UART_packet_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/test_UART_packet/ip/test_UART_packet_AXI4Stream_UART_0_1/test_UART_packet_AXI4Stream_UART_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_UART_packet_AXI4Stream_UART_0_1 || ORIG_REF_NAME==test_UART_packet_AXI4Stream_UART_0_1} -quiet] -quiet

# IP: bd/test_UART_packet/ip/test_UART_packet_axi4stream_spi_master_0_1/test_UART_packet_axi4stream_spi_master_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_UART_packet_axi4stream_spi_master_0_1 || ORIG_REF_NAME==test_UART_packet_axi4stream_spi_master_0_1} -quiet] -quiet

# IP: bd/test_UART_packet/ip/test_UART_packet_clk_wiz_0_2/test_UART_packet_clk_wiz_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_UART_packet_clk_wiz_0_2 || ORIG_REF_NAME==test_UART_packet_clk_wiz_0_2} -quiet] -quiet

# IP: bd/test_UART_packet/ip/test_UART_packet_jstk_uart_bridge_0_0_1/test_UART_packet_jstk_uart_bridge_0_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_UART_packet_jstk_uart_bridge_0_0_1 || ORIG_REF_NAME==test_UART_packet_jstk_uart_bridge_0_0_1} -quiet] -quiet

# IP: bd/test_UART_packet/ip/test_UART_packet_digilent_jstk2_0_1/test_UART_packet_digilent_jstk2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_UART_packet_digilent_jstk2_0_1 || ORIG_REF_NAME==test_UART_packet_digilent_jstk2_0_1} -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/jstk2_interface/jstk2_interface.gen/sources_1/bd/test_UART_packet/test_UART_packet_ooc.xdc
