# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Joystick_SPI_tester/Joystick_SPI_tester.srcs/sources_1/bd/joysticktester/ip/joysticktester_proc_sys_reset_0_1/joysticktester_proc_sys_reset_0_1.xci
# IP: The module: 'joysticktester_proc_sys_reset_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Joystick_SPI_tester/Joystick_SPI_tester.gen/sources_1/bd/joysticktester/ip/joysticktester_proc_sys_reset_0_1/joysticktester_proc_sys_reset_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'joysticktester_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Joystick_SPI_tester/Joystick_SPI_tester.gen/sources_1/bd/joysticktester/ip/joysticktester_proc_sys_reset_0_1/joysticktester_proc_sys_reset_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'joysticktester_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Joystick_SPI_tester/Joystick_SPI_tester.gen/sources_1/bd/joysticktester/ip/joysticktester_proc_sys_reset_0_1/joysticktester_proc_sys_reset_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'joysticktester_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Joystick_SPI_tester/Joystick_SPI_tester.srcs/sources_1/bd/joysticktester/ip/joysticktester_proc_sys_reset_0_1/joysticktester_proc_sys_reset_0_1.xci
# IP: The module: 'joysticktester_proc_sys_reset_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Joystick_SPI_tester/Joystick_SPI_tester.gen/sources_1/bd/joysticktester/ip/joysticktester_proc_sys_reset_0_1/joysticktester_proc_sys_reset_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'joysticktester_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Joystick_SPI_tester/Joystick_SPI_tester.gen/sources_1/bd/joysticktester/ip/joysticktester_proc_sys_reset_0_1/joysticktester_proc_sys_reset_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'joysticktester_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Joystick_SPI_tester/Joystick_SPI_tester.gen/sources_1/bd/joysticktester/ip/joysticktester_proc_sys_reset_0_1/joysticktester_proc_sys_reset_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'joysticktester_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
