# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Pinout_SPI.xdc

# Block Designs: bd/joysticktester/joysticktester.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==joysticktester || ORIG_REF_NAME==joysticktester} -quiet] -quiet

# IP: bd/joysticktester/ip/joysticktester_clk_wiz_0_0/joysticktester_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==joysticktester_clk_wiz_0_0 || ORIG_REF_NAME==joysticktester_clk_wiz_0_0} -quiet] -quiet

# IP: bd/joysticktester/ip/joysticktester_proc_sys_reset_0_1/joysticktester_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==joysticktester_proc_sys_reset_0_1 || ORIG_REF_NAME==joysticktester_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/joysticktester/ip/joysticktester_axi4stream_spi_master_0_1/joysticktester_axi4stream_spi_master_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==joysticktester_axi4stream_spi_master_0_1 || ORIG_REF_NAME==joysticktester_axi4stream_spi_master_0_1} -quiet] -quiet

# IP: bd/joysticktester/ip/joysticktester_digilent_jstk2_0_1/joysticktester_digilent_jstk2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==joysticktester_digilent_jstk2_0_1 || ORIG_REF_NAME==joysticktester_digilent_jstk2_0_1} -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/Git/KittCarPWM/Joystick_SPI_tester/Joystick_SPI_tester.gen/sources_1/bd/joysticktester/joysticktester_ooc.xdc
