# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Pins.xdc

# Block Designs: bd/Color2Grey/Color2Grey.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Color2Grey || ORIG_REF_NAME==Color2Grey} -quiet] -quiet

# IP: bd/Color2Grey/ip/Color2Grey_clk_wiz_0_0/Color2Grey_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Color2Grey_clk_wiz_0_0 || ORIG_REF_NAME==Color2Grey_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Color2Grey/ip/Color2Grey_proc_sys_reset_0_0/Color2Grey_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Color2Grey_proc_sys_reset_0_0 || ORIG_REF_NAME==Color2Grey_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Color2Grey/ip/Color2Grey_AXI4Stream_UART_0_0/Color2Grey_AXI4Stream_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Color2Grey_AXI4Stream_UART_0_0 || ORIG_REF_NAME==Color2Grey_AXI4Stream_UART_0_0} -quiet] -quiet

# IP: bd/Color2Grey/ip/Color2Grey_C2G_0_0/Color2Grey_C2G_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Color2Grey_C2G_0_0 || ORIG_REF_NAME==Color2Grey_C2G_0_0} -quiet] -quiet

# XDC: c:/Users/daido/Desktop/Polimi/Anno 4/DESD/LAB2/Color2Grey/Color2Grey.gen/sources_1/bd/Color2Grey/Color2Grey_ooc.xdc
